module.exports.unlessRoutes = {
  path: [
    { url: "/api/v2/auth/login", method: "POST" },
    { url: "/api/v2/report/order", method: "GET" },
    { url: "/api/v2/auth/register", method: "POST" },
    { url: "/api/v2/auth/refresh", method: "POST" },
    // { url: "/api/v2/checkout", method: "POST" },
    { url: "/api/v2/shipmentTracking/download-orders", method: "GET" },
    { url: "/api/v2/checkout/test", method: "GET" },
    { url: "/api/v2/brand", method: "GET" },
    { url: /^\/api\/v2\/brand\/.*/, method: "GET" },
    { url: /^\/api\/v2\/review(?:\/.*)?$/, method: "GET" },

    { url: "/api/v2/review", method: "POST" },
    { url: "/api/v2/cart", method: "GET" },
    { url: /^\/api\/v2\/cart\/.*/, method: "GET" },
    { url: /^\/api\/v2\/product\/.*/, method: "GET" },
    { url: "/api/v2/product", method: "GET" },
    { url: /^\/api\/v2\/shippingProvider\/.*/, method: "GET" },
    { url: "/api/v2/shippingProvider", method: "GET" },
    { url: /^\/api\/v2\/user\/.*/, method: "GET" },
    { url: "/api/v2/order", method: "GET" },
    { url: "/api/v2/order/convert-to-excel", method: "GET" },
    { url: "/api/v2/coupon", method: "GET" },
    { url: /^\/api\/v2\/coupon\/.*/, method: "GET" },
    { url: /^\/api\/v2\/attribute\/.*/, method: "GET" },
    { url: "/api/v2/accountPrivacy", method: "GET" },
    { url: "/api/v2/category", method: "GET" },
    { url: /^\/api\/v2\/category\/.*/, method: "GET" },
    { url: "/api/v2/product/by-variation", method: "POST" },
    { url: "/api/v2/filter/products", method: "POST" },
    { url: "/api/v2/shippingzone/shipping-cost", method: "POST" },
  ],
};
